const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const crypto=require('crypto');
const path=require('path');
const fs=require('fs');
const app=express();
const server=http.createServer(app);
const io=new Server(server,{maxHttpBufferSize:20e6,pingInterval:10000,pingTimeout:20000});
const rooms=new Map();
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'kashikoihito';
const adminTokens=new Set();
function isAdmin(req){return adminTokens.has(String(req.get('x-admin-token')||''))}
const DATA_DIR=path.join(__dirname,'data');
const SETS_FILE=path.join(DATA_DIR,'problem_sets.json');
const ADDITIONAL_FILE=path.join(DATA_DIR,'additional_problems.json');
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
let problemSets=[];try{problemSets=JSON.parse(fs.readFileSync(SETS_FILE,'utf8'));if(!Array.isArray(problemSets))problemSets=[]}catch(e){problemSets=[]}
let additionalProblems=[];try{additionalProblems=JSON.parse(fs.readFileSync(ADDITIONAL_FILE,'utf8'));if(!Array.isArray(additionalProblems))additionalProblems=[]}catch(e){additionalProblems=[]}
let db=null;let dbReady=Promise.resolve();
if(process.env.DATABASE_URL){const {Pool}=require('pg');db=new Pool({connectionString:process.env.DATABASE_URL,max:5,idleTimeoutMillis:30000,connectionTimeoutMillis:5000});dbReady=(async()=>{await db.query(`CREATE TABLE IF NOT EXISTS problem_sets (id TEXT PRIMARY KEY,name TEXT NOT NULL,questions JSONB NOT NULL,updated_at BIGINT NOT NULL)`);await db.query(`CREATE TABLE IF NOT EXISTS additional_problems (id TEXT PRIMARY KEY,text TEXT NOT NULL,image TEXT NOT NULL,updated_at BIGINT NOT NULL)`);const count=(await db.query('SELECT COUNT(*)::int AS n FROM problem_sets')).rows[0].n;if(count===0&&problemSets.length)for(const x of problemSets)await db.query('INSERT INTO problem_sets(id,name,questions,updated_at) VALUES($1,$2,$3,$4) ON CONFLICT (id) DO NOTHING',[x.id,x.name,JSON.stringify(x.questions||[]),x.updatedAt||Date.now()]);const acount=(await db.query('SELECT COUNT(*)::int AS n FROM additional_problems')).rows[0].n;if(acount===0&&additionalProblems.length)for(const x of additionalProblems)await db.query('INSERT INTO additional_problems(id,text,image,updated_at) VALUES($1,$2,$3,$4) ON CONFLICT (id) DO NOTHING',[x.id,x.text,x.image||'',x.updatedAt||Date.now()])})().catch(e=>{console.error('DATABASE INIT ERROR',e);process.exit(1)})}
function saveProblemSets(){fs.writeFileSync(SETS_FILE,JSON.stringify(problemSets,null,2),'utf8')}
function publicSet(x){return{id:x.id,name:x.name,questions:x.questions,updatedAt:x.updatedAt}}
async function getProblemSets(){await dbReady;if(!db)return problemSets;const rows=(await db.query('SELECT id,name,questions,updated_at FROM problem_sets ORDER BY updated_at ASC')).rows;return rows.map(r=>({id:r.id,name:r.name,questions:r.questions,updatedAt:Number(r.updated_at)}))}
async function insertProblemSet(x){await dbReady;if(!db){problemSets.push(x);saveProblemSets();return x}await db.query('INSERT INTO problem_sets(id,name,questions,updated_at) VALUES($1,$2,$3,$4)',[x.id,x.name,JSON.stringify(x.questions),x.updatedAt]);return x}
async function updateProblemSet(id,name,questions){await dbReady;if(!db){const x=problemSets.find(v=>v.id===id);if(!x)return null;x.name=name;x.questions=questions;x.updatedAt=Date.now();saveProblemSets();return x}const r=await db.query('UPDATE problem_sets SET name=$1,questions=$2,updated_at=$3 WHERE id=$4 RETURNING id,name,questions,updated_at',[name,JSON.stringify(questions),Date.now(),id]);if(!r.rowCount)return null;const x=r.rows[0];return{id:x.id,name:x.name,questions:x.questions,updatedAt:Number(x.updated_at)}}
async function deleteProblemSet(id){await dbReady;if(!db){const n=problemSets.length;problemSets=problemSets.filter(v=>v.id!==id);if(problemSets.length===n)return false;saveProblemSets();return true}return(await db.query('DELETE FROM problem_sets WHERE id=$1',[id])).rowCount>0}
async function getAdditionalProblems(){await dbReady;if(!db)return additionalProblems;const rows=(await db.query('SELECT id,text,image,updated_at FROM additional_problems ORDER BY updated_at ASC')).rows;return rows.map(r=>({id:r.id,text:r.text,image:r.image||'',updatedAt:Number(r.updated_at)}))}
async function insertAdditionalProblem(x){await dbReady;if(!db){additionalProblems.push(x);fs.writeFileSync(ADDITIONAL_FILE,JSON.stringify(additionalProblems,null,2),'utf8');return x}await db.query('INSERT INTO additional_problems(id,text,image,updated_at) VALUES($1,$2,$3,$4)',[x.id,x.text,x.image||'',x.updatedAt]);return x}
async function updateAdditionalProblem(id,text,image){await dbReady;if(!db){const x=additionalProblems.find(v=>v.id===id);if(!x)return null;x.text=text;x.image=image||'';x.updatedAt=Date.now();fs.writeFileSync(ADDITIONAL_FILE,JSON.stringify(additionalProblems,null,2),'utf8');return x}const r=await db.query('UPDATE additional_problems SET text=$1,image=$2,updated_at=$3 WHERE id=$4 RETURNING id,text,image,updated_at',[text,image||'',Date.now(),id]);if(!r.rowCount)return null;const x=r.rows[0];return{id:x.id,text:x.text,image:x.image||'',updatedAt:Number(x.updated_at)}}
async function deleteAdditionalProblem(id){await dbReady;if(!db){const n=additionalProblems.length;additionalProblems=additionalProblems.filter(v=>v.id!==id);if(additionalProblems.length===n)return false;fs.writeFileSync(ADDITIONAL_FILE,JSON.stringify(additionalProblems,null,2),'utf8');return true}return(await db.query('DELETE FROM additional_problems WHERE id=$1',[id])).rowCount>0}
function publicAdditional(x){return{id:x.id,text:x.text,image:x.image||'',updatedAt:x.updatedAt}}
const ROOM_TTL=30*60*1000,QUESTION_SECONDS=80,GAME_SECONDS=15*60,AUTO_NEXT_MS=6000;
app.use(express.json({limit:'20mb'}));
app.get('/api/problem-sets',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});try{const sets=await getProblemSets();res.json(sets.map(publicSet))}catch(e){console.error(e);res.status(500).json({error:'問題集の読み込みに失敗しました。'})}});
app.post('/api/problem-sets',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});const name=String(req.body?.name||'').trim().slice(0,60),qs=Array.isArray(req.body?.questions)?req.body.questions.map(normalizeQuestion).filter(q=>q.text.trim()).slice(0,5):[];if(!name||qs.length!==5)return res.status(400).json({error:'セット名と5問が必要です。'});const x={id:crypto.randomBytes(8).toString('hex'),name,questions:qs,updatedAt:Date.now()};try{await insertProblemSet(x);res.json(publicSet(x))}catch(e){console.error(e);res.status(500).json({error:'問題集の保存に失敗しました。'})}});
app.put('/api/problem-sets/:id',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});const name=String(req.body?.name||'').trim().slice(0,60),qs=Array.isArray(req.body?.questions)?req.body.questions.map(normalizeQuestion).filter(q=>q.text.trim()).slice(0,5):[];if(!name||qs.length!==5)return res.status(400).json({error:'セット名と5問が必要です。'});try{const x=await updateProblemSet(req.params.id,name,qs);if(!x)return res.status(404).json({error:'セットが見つかりません。'});res.json(publicSet(x))}catch(e){console.error(e);res.status(500).json({error:'問題集の更新に失敗しました。'})}});
app.delete('/api/problem-sets/:id',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});try{if(!await deleteProblemSet(req.params.id))return res.status(404).json({error:'セットが見つかりません。'});res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'問題集の削除に失敗しました。'})}});
app.post('/api/problem-sets/import',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});try{const incoming=Array.isArray(req.body?.sets)?req.body.sets:[];if(!incoming.length)return res.json({ok:true,imported:0});const existing=await getProblemSets(),ids=new Set(existing.map(x=>x.id));let imported=0;for(const raw of incoming){const id=String(raw?.id||''),name=String(raw?.name||'').trim().slice(0,60),qs=Array.isArray(raw?.questions)?raw.questions.map(normalizeQuestion).filter(q=>q.text.trim()).slice(0,5):[];if(!id||!name||qs.length!==5||ids.has(id))continue;await insertProblemSet({id,name,questions:qs,updatedAt:Number(raw?.updatedAt)||Date.now()});ids.add(id);imported++}res.json({ok:true,imported})}catch(e){console.error(e);res.status(500).json({error:'問題集の移行に失敗しました。'})}});
app.get('/api/additional-problems',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});try{const xs=await getAdditionalProblems();res.json(xs.map(publicAdditional))}catch(e){console.error(e);res.status(500).json({error:'追加問題の読み込みに失敗しました。'})}});
app.post('/api/additional-problems',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});const text=String(req.body?.text||'').trim().slice(0,300),image=typeof req.body?.image==='string'?req.body.image:'';if(!text)return res.status(400).json({error:'問題文を入力してください。'});const x={id:crypto.randomBytes(8).toString('hex'),text,image,updatedAt:Date.now()};try{await insertAdditionalProblem(x);res.json(publicAdditional(x))}catch(e){console.error(e);res.status(500).json({error:'追加問題の保存に失敗しました。'})}});
app.put('/api/additional-problems/:id',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});const text=String(req.body?.text||'').trim().slice(0,300),image=typeof req.body?.image==='string'?req.body.image:'';if(!text)return res.status(400).json({error:'問題文を入力してください。'});try{const x=await updateAdditionalProblem(req.params.id,text,image);if(!x)return res.status(404).json({error:'追加問題が見つかりません。'});res.json(publicAdditional(x))}catch(e){console.error(e);res.status(500).json({error:'追加問題の更新に失敗しました。'})}});
app.delete('/api/additional-problems/:id',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});try{if(!await deleteAdditionalProblem(req.params.id))return res.status(404).json({error:'追加問題が見つかりません。'});res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'追加問題の削除に失敗しました。'})}});
app.post('/api/additional-problems/import',async(req,res)=>{if(!isAdmin(req))return res.status(401).json({error:'司会者ログインが必要です。'});try{const incoming=Array.isArray(req.body?.problems)?req.body.problems:[];if(!incoming.length)return res.json({ok:true,imported:0});const existing=await getAdditionalProblems(),ids=new Set(existing.map(x=>x.id));let imported=0;for(const raw of incoming){const id=String(raw?.id||''),text=String(raw?.text||'').trim().slice(0,300),image=typeof raw?.image==='string'?raw.image:'';if(!id||!text||ids.has(id))continue;await insertAdditionalProblem({id,text,image,updatedAt:Number(raw?.updatedAt)||Date.now()});ids.add(id);imported++}res.json({ok:true,imported})}catch(e){console.error(e);res.status(500).json({error:'追加問題の移行に失敗しました。'})}});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'open-quiz',hasDatabase:!!db,host:req.headers.host||'',protocol:req.headers['x-forwarded-proto']||'http'}));app.use(express.static(path.join(__dirname,'public')));app.get('/display',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const makeCode=()=>crypto.randomBytes(3).toString('hex').toUpperCase(),makeToken=()=>crypto.randomBytes(18).toString('hex');
const normalizeQuestion=q=>typeof q==='string'?{text:String(q).slice(0,300),image:''}:{text:String(q?.text||'').slice(0,300),image:typeof q?.image==='string'?q.image:''};
function currentQuestion(r){return r.questions[r.current-1]||{text:'',image:''}}
function publicPlayers(r){return [...r.players.values()].map(p=>({id:p.id,name:p.name,locked:p.locked,connected:p.connected!==false,helpUsed:p.helpUsed}))}
function statePayload(r){const payload={roomName:r.name,current:r.current,total:r.questions.length,question:currentQuestion(r),phase:r.phase,remaining:r.remaining,gameRemaining:r.gameRemaining,paused:r.paused,players:publicPlayers(r),helpActive:r.helpActive?{name:r.helpActive.name,question:r.helpActive.question}:null};if(r.phase==='reveal')payload.published=[...r.players.values()].map(p=>({id:p.id,name:p.name,answer:p.answer||'',result:(r.results.get(r.current)||{})[p.token]}));if(r.phase==='final')payload.final=finalSummary(r);return payload}
function emitState(code){const r=rooms.get(code);if(r)io.to(code).emit('state',statePayload(r))}
function stopQuestionTimer(r){if(r.timer){clearInterval(r.timer);r.timer=null}}
function stopGameTimer(r){if(r.gameTimer){clearInterval(r.gameTimer);r.gameTimer=null}}
function clearAdvance(r){if(r.advanceTimer){clearTimeout(r.advanceTimer);r.advanceTimer=null}}
function startQuestionTimer(code,reset=true){const r=rooms.get(code);if(!r)return;stopQuestionTimer(r);if(reset)r.remaining=QUESTION_SECONDS;emitState(code);r.timer=setInterval(()=>{if(r.phase!=='answer'||r.paused){return}r.remaining=Math.max(0,r.remaining-1);io.to(code).emit('timer',{remaining:r.remaining});if(r.remaining===0){stopQuestionTimer(r);for(const p of r.players.values())if(!p.locked){p.locked=true;p.answer=p.answer||''}r.phase='answerEnded';emitState(code);if(r.host)io.to(r.host).emit('timeUp')}},1000)}
function startGameTimer(code,reset=true){const r=rooms.get(code);if(!r)return;stopGameTimer(r);if(reset)r.gameRemaining=GAME_SECONDS;io.to(code).emit('gameTimer',{remaining:r.gameRemaining});r.gameTimer=setInterval(()=>{if(r.phase==='final'||r.paused)return;r.gameRemaining=Math.max(0,r.gameRemaining-1);io.to(code).emit('gameTimer',{remaining:r.gameRemaining});if(r.gameRemaining===0){stopGameTimer(r);stopQuestionTimer(r);for(const p of r.players.values())if(!p.locked){p.locked=true;p.answer=p.answer||''}r.phase='answerEnded';emitState(code);if(r.host)io.to(r.host).emit('gameTimeUp')}},1000)}
function newQuestion(code){const r=rooms.get(code);if(!r)return;clearAdvance(r);stopQuestionTimer(r);r.phase='answer';r.helpActive=null;for(const p of r.players.values()){p.locked=false;p.answer=''}startQuestionTimer(code,true);io.to(code).emit('question',{number:r.current,total:r.questions.length,...currentQuestion(r)});emitState(code)}
function finalSummary(r){const rows=[...r.players.values()].map(p=>{let score=0;for(const g of r.results.values())if(g[p.token]==='correct')score++;return{id:p.id,name:p.name,score}});return{rows:rows.sort((a,b)=>b.score-a.score)}}
function scheduleAutoAdvance(code){const r=rooms.get(code);if(!r)return;clearAdvance(r);r.advanceTimer=setTimeout(()=>{const x=rooms.get(code);if(!x||x.phase!=='reveal')return;if(x.current>=x.questions.length){x.phase='final';stopGameTimer(x);io.to(code).emit('final',finalSummary(x));emitState(code)}else{x.current++;newQuestion(code)}},AUTO_NEXT_MS)}
function cleanupRoom(code){const r=rooms.get(code);if(!r)return;stopQuestionTimer(r);stopGameTimer(r);clearAdvance(r);rooms.delete(code);emitDisplayRoomList()}
function scheduleCleanup(code){const r=rooms.get(code);if(!r)return;r.cleanupAt=Date.now()+ROOM_TTL;setTimeout(()=>{const x=rooms.get(code);if(x&&x.cleanupAt<=Date.now())cleanupRoom(code)},ROOM_TTL+100)}
function displayRooms(){return [...rooms.entries()].filter(([_,r])=>r.phase!=='final').map(([code,r])=>({code,name:r.name||'OPEN QUIZ',players:r.players.size,maxPlayers:8,phase:r.phase,started:r.phase!=='setup',current:r.current,total:r.questions.length,paused:r.paused})).sort((a,b)=>a.started-b.started||a.name.localeCompare(b.name,'ja'))}
function emitDisplayRoomList(){io.to('displayLobby').emit('displayRooms',displayRooms())}
io.on('connection',s=>{
  s.on('authHost',d=>{if(String(d?.password||'')!==ADMIN_PASSWORD)return s.emit('authFailed',{role:'host',message:'パスワードが違います。'});const token=makeToken();adminTokens.add(token);s.data.adminToken=token;s.data.adminRole='host';s.emit('authOk',{role:'host',token})});
  s.on('authDisplay',d=>{if(String(d?.password||'')!==ADMIN_PASSWORD)return s.emit('authFailed',{role:'display',message:'パスワードが違います。'});s.data.adminRole='display';s.join('displayLobby');s.emit('authOk',{role:'display'});emitDisplayRoomList()});
  s.on('listDisplayRooms',()=>{if(s.data.adminRole!=='display')return;s.join('displayLobby');s.emit('displayRooms',displayRooms())});
  s.on('create',async d=>{if(s.data.adminRole!=='host')return s.emit('err','司会者ログインが必要です。');let code;do code=makeCode();while(rooms.has(code));const hostToken=makeToken(),setId=String(d?.setId||'');let selected=null;try{selected=(await getProblemSets()).find(x=>x.id===setId)||null}catch(e){return s.emit('err','問題集の読み込みに失敗しました。')}const questions=selected?selected.questions.map(normalizeQuestion):[{text:'',image:''}],name=String(d?.name||selected?.name||'OPEN QUIZ').trim().slice(0,60)||'OPEN QUIZ';const r={host:s.id,hostToken,name,questions,current:1,phase:'setup',players:new Map(),results:new Map(),remaining:QUESTION_SECONDS,gameRemaining:GAME_SECONDS,timer:null,gameTimer:null,advanceTimer:null,cleanupAt:0,paused:false,helpActive:null};rooms.set(code,r);s.data.room=code;s.data.role='host';s.data.hostToken=hostToken;s.join(code);const publicBase=(process.env.PUBLIC_URL||'').replace(/\/$/,'')||null;const base=publicBase||(('https'===String(s.handshake.headers['x-forwarded-proto']||'')?'https':'http')+'://'+s.handshake.headers.host);s.emit('created',{code,token:hostToken,setId:selected?.id||'',name,playerUrl:base+'/?room='+code+'&mode=player',displayUrl:base+'/display?room='+code});emitState(code);emitDisplayRoomList()});
  s.on('resumeHost',d=>{if(s.data.adminRole!=='host')return s.emit('err','司会者ログインが必要です。');const code=String(d?.code||'').toUpperCase(),r=rooms.get(code);if(!r||r.hostToken!==d?.token)return s.emit('err','司会者の再接続情報が見つかりません。');r.host=s.id;s.data.room=code;s.data.role='host';s.data.hostToken=d.token;s.join(code);r.cleanupAt=0;emitState(code);if(r.phase==='answer'&&r.remaining>0)startQuestionTimer(code,false);if(r.phase!=='final'&&r.gameRemaining>0)startGameTimer(code,false);s.emit('resumedHost')});
  s.on('joinDisplay',d=>{if(s.data.adminRole!=='display')return s.emit('displayError','プロジェクターログインが必要です。');const code=String(d?.roomCode||'').trim().toUpperCase(),r=rooms.get(code);if(!r)return s.emit('displayError','そのクイズは見つかりません。');s.data.room=code;s.data.role='display';s.join(code);s.emit('displayJoined',{code,name:r.name});s.emit('state',statePayload(r))});
  s.on('join',d=>{const code=String(d?.code||'').trim().toUpperCase(),r=rooms.get(code);if(!r)return s.emit('err','部屋がありません。');if(r.phase!=='setup')return s.emit('err','このクイズはすでにスタートしています。');if(r.players.size>=8)return s.emit('err','8人で満員です。');const token=makeToken(),p={id:s.id,token,name:String(d?.name||'PLAYER').trim().slice(0,20)||'PLAYER',locked:false,answer:'',connected:true,helpUsed:false};r.players.set(token,p);s.data.room=code;s.data.role='player';s.data.playerToken=token;s.join(code);s.emit('joined',{number:r.current,total:r.questions.length,text:'',image:'',token,phase:r.phase,locked:false,helpUsed:false});emitState(code);emitDisplayRoomList()});
  s.on('resumePlayer',d=>{const code=String(d?.code||'').toUpperCase(),r=rooms.get(code),p=r&&r.players.get(d?.token);if(!r||!p)return s.emit('err','参加情報が見つかりません。');p.id=s.id;p.connected=true;s.data.room=code;s.data.role='player';s.data.playerToken=d.token;s.join(code);r.cleanupAt=0;s.emit('resumedPlayer',{number:r.current,total:r.questions.length,...(r.phase==='setup'?{text:'',image:''}:currentQuestion(r)),locked:p.locked,phase:r.phase,helpUsed:p.helpUsed});emitState(code);if(r.phase==='reveal'){const result=r.results.get(r.current)?.[p.token];if(result)s.emit('myVerdict',{number:r.current,result})}});
  s.on('questions',qs=>{if(s.data.adminRole!=='host')return;const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.phase!=='setup')return;const a=Array.isArray(qs)?qs.map(normalizeQuestion).filter((q,i)=>i<20&&q.text.trim()):[];if(!a.length)return s.emit('err','1問以上入力してください。');r.questions=a;r.current=1;r.results=new Map();emitState(s.data.room);emitDisplayRoomList()});
  s.on('startGame',()=>{if(s.data.adminRole!=='host')return;const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.phase!=='setup')return;if(!r.players.size)return s.emit('err','参加者が1人以上必要です。');if(r.questions.some(q=>!q.text.trim()))return s.emit('err','問題文を確認してください。');r.paused=false;r.gameRemaining=GAME_SECONDS;startGameTimer(s.data.room);newQuestion(s.data.room);emitDisplayRoomList()});
  s.on('lock',answer=>{const r=rooms.get(s.data.room),p=r&&r.players.get(s.data.playerToken);if(!r||!p||r.phase!=='answer'||r.paused||p.locked)return;p.locked=true;p.answer=String(answer||'').slice(0,800000);emitState(s.data.room)});
  s.on('help',()=>{const r=rooms.get(s.data.room),p=r&&r.players.get(s.data.playerToken);if(!r||!p||r.phase!=='answer'||r.paused||p.locked||p.helpUsed||r.helpActive)return;p.helpUsed=true;r.helpActive={token:p.token,name:p.name,question:r.current};io.to(r.host||'__none__').emit('helpRequested',{name:p.name,question:r.current});for(const [id] of rooms){if(id===s.data.room)io.to(id).emit('helpActive',{name:p.name,question:r.current})}emitState(s.data.room)});
  s.on('clearHelp',()=>{if(s.data.adminRole!=='host')return;const r=rooms.get(s.data.room);if(!r||r.host!==s.id)return;r.helpActive=null;io.to(s.data.room).emit('helpCleared');emitState(s.data.room)});
  s.on('togglePause',()=>{if(s.data.adminRole!=='host')return;const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.phase==='final')return;r.paused=!r.paused;io.to(s.data.room).emit('paused',{paused:r.paused});emitState(s.data.room)});
  s.on('startGrading',()=>{if(s.data.adminRole!=='host')return;const r=rooms.get(s.data.room);if(!r||r.host!==s.id)return;if(!r.players.size||[...r.players.values()].some(p=>!p.locked))return s.emit('err','全員のLOCKを待ってください。');stopQuestionTimer(r);r.phase='grading';const rows=[...r.players.values()].map(p=>({id:p.id,name:p.name,answer:p.answer||''}));io.to(r.host).emit('grading',rows);io.to(s.data.room).emit('gradingStarted');emitState(s.data.room)});
  s.on('publishGrades',grades=>{if(s.data.adminRole!=='host')return;const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.phase!=='grading')return;const g={};for(const p of r.players.values()){if(!grades||!['correct','wrong'].includes(grades[p.id]))return s.emit('err','全員の〇×を決めてください。');g[p.token]=grades[p.id]}r.results.set(r.current,g);r.phase='reveal';const published=[...r.players.values()].map(p=>({id:p.id,name:p.name,answer:p.answer||'',result:g[p.token]}));io.to(r.host).emit('published',published);io.to(s.data.room).emit('revealPublished',published);for(const p of r.players.values())if(p.id)io.to(p.id).emit('myVerdict',{number:r.current,result:g[p.token]});emitState(s.data.room);scheduleAutoAdvance(s.data.room)});
  s.on('addAdditionalQuestion',async d=>{if(s.data.adminRole!=='host')return;const r=rooms.get(s.data.room);if(!r||r.host!==s.id||r.phase!=='reveal')return;if(r.current!==r.questions.length)return s.emit('err','追加問題はセット終了後に選べます。');const id=String(d?.id||'');try{const x=(await getAdditionalProblems()).find(v=>v.id===id);if(!x)return s.emit('err','追加問題が見つかりません。');clearAdvance(r);r.questions.push(normalizeQuestion(x));r.current=r.questions.length;newQuestion(s.data.room)}catch(e){console.error(e);s.emit('err','追加問題の読み込みに失敗しました。')}});
  s.on('reset',()=>{if(s.data.adminRole!=='host')return;const r=rooms.get(s.data.room);if(!r||r.host!==s.id)return;if(r.phase==='setup'){return}r.paused=false;newQuestion(s.data.room)});
  s.on('disconnect',()=>{const code=s.data.room,r=code&&rooms.get(code);if(!r)return;if(r.host===s.id){r.host=null;io.to(code).emit('hostDisconnected');scheduleCleanup(code)}else if(s.data.role==='player'){const p=r.players.get(s.data.playerToken);if(p){p.connected=false;p.id=null}emitState(code);scheduleCleanup(code)}});
});
server.listen(process.env.PORT||3000,()=>console.log('OPEN QUIZ improved running'));
